language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - dotnet restore LinqInfer.sln
  - dotnet build LinqInfer.sln
  - dotnet test tests/LinqInfer.UnitTests/LinqInfer.UnitTests.csproj --filter TestCategory!=BuildOmit
  - dotnet test tests/LinqInfer.IntegrationTests/LinqInfer.IntegrationTests.csproj --filter TestCategory!=BuildOmit