language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - dotnet restore LinqInfer.sln
  - dotnet build tests/LinqInfer.UnitTests/LinqInfer.UnitTests.csproj
  - dotnet test tests/LinqInfer.UnitTests/LinqInfer.UnitTests.csproj --filter TestCategory!=BuildOmit