language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
  - dotnet restore LinqInfer.sln
  - dotnet build tests/LinqInfer.Tests/LinqInfer.Tests.csproj
  - dotnet test tests/LinqInfer.Tests/LinqInfer.Tests.csproj