# Builds and runs tests

FROM microsoft/dotnet:2.0.4-sdk-2.1.3

WORKDIR /app

COPY ./build /app/build
COPY ./src /app/src
COPY ./tests /app/tests
COPY ./LinqInfer.sln /app

EXPOSE 8083

WORKDIR ./build
RUN ./build-docker.sh

WORKDIR ../

# ENV VAR? ${LOCAL_IP_AND_PORT}

CMD dotnet run -f netcoreapp1.1 -p ./tests/LinqInfer.AspNetCoreTestHarness/LinqInfer.AspNetCoreTestHarness.csproj -- http://0.0.0.0:8083/
